### ISSUE TITLE
To-Do By April 9

### ISSUE THREAD

**Issue by simonpcouch** [ds-civic-data/bikeshare-1#1]
- [x] Write master query function, decide on file structure
- [x] Check this function with Kristin
- Call Biketown to ask about historical data (done, but no longer applicable)
- Actually initialize function and start collecting historical data (no longer applicable)
- [x] Solidify deliverables in R package (as it relates to Shiny and what we can get from Biketown)
